sudo: false
dist: xenial
language: python
cache: pip
python:
  - '3.7'
install:
- pip install --upgrade pip codecov
- pip install --upgrade -e .[dev]
- python3 setup.py build
script:
- pytest
after_success:
- codecov
notifications:
  email: false
